CREATE TABLE `Entries` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`body`	TEXT NOT NULL,
	`date`	INTEGER NOT NULL,
    `mood_id` INTEGER NOT NULL FOREIGN KEY
);

-- HAVE NOT RUN YET. VERIFY MOODS
CREATE TABLE `moods` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`mood`	TEXT NOT NULL
);

-- HAVE NOT RUN YET. ADD ONE FOR MOODS TOO
INSERT INTO `Entries` VALUES (null, 'journal entry body', 04182021, 5);